### ISSUE TITLE
Skylake Intel265 Encoding?

### ISSUE THREAD

**Issue by karl0ss** [Anime4000/IFME#108]
I can't work it out, but does IFME support hardware accelerated 265 encoding for Skylake> (QuickSyncVideo) processors?

As I have enabled intel in the settings, but my encodes are taking 2hours where on staxrip its being done in about 30mins...

**Comment by karl0ss** [comment]
Is this closed as its a bug and not being fixed? or am i missing something?

Thanks

**Comment by Anime4000** [comment]
IFME heavily depend on FFmpeg and MulticoreWare H.265, which both of them using CPU based encoding.

Using Hardware Accelerate encoding wont give you lower bit-rate at higher quality, as this video explain: https://www.youtube.com/watch?v=BV5btdqQfu4

Here plugin for IFME 7.x simply put `plugin` folder, I can't test since I don't have compatible CPU, so you can modify `_plugin.json` to make it work.

[video.h264qsv.ffmpeg.zip](https://github.com/Anime4000/IFME/files/1101910/video.h264qsv.ffmpeg.zip)

More info can be found here:
https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by Anime4000** [comment]
Hardware encode plugin for [IFME 7.x](https://sourceforge.net/projects/ifme/files/plugin/plugin-hwenc_2017-06-27.7z/download)

I don't have Intel CPU to test, so please try 😺 
I closing this issue, if not fix, feel free to re-open :)
