### ISSUE TITLE
Encoder Video Definition

### ISSUE THREAD

**Issue by Alexisback** [Anime4000/IFME#113]
does anyone know how to explain the definitions of these settings?

```
[video]
ext = hevc
bitdepth = 8,10,12
preset = ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow,placebo
tune = psnr,ssim,grain,zerolatency,fastdecode
mode = 3
```

unfortunately not a guide to understanding

are not practical, and the first time i approach to encoding video

thanks

**Comment by thefinaldegree** [comment]
I would suggest heading to Google as there are many great guides already
online. I found this one that seems to be good for the first timer to
encoding:
http://www.streamingmedia.com/Articles/Editorial/Featured-Articles/How-to-Encode-to-HEVC-A-Simple-Guide-for-H.265-First-Timers-102507.aspx

**Comment by Alexisback** [comment]
thank
it would take an official guide for IFME

**Comment by thefinaldegree** [comment]
I would say it's up to Anime4000 whether there will be any sort of official
encoding guide.

**Comment by Anime4000** [comment]
@Alexisback please use IFME 7 from now on, I using JSON instead of INI format for plugin definition, any changes I make in the future will not crash

I am sorry for no "Guide" or "Documentation" and my english grammar weak to make documentation, but I can try to make one and correction are welcome 😄 (I hope I can learn proper english)

**Comment by Alexisback** [comment]
hello Anime4000
Also my English and bad,
version 7, however, and beta and limited function

**Comment by Alexisback** [comment]
I did a couple of tests with version 6
the result is good, however, the definition of the details and a bit blurry
how to adjust this?

**Comment by thefinaldegree** [comment]
That's likely to be leftover from the DVD source. A low quality (lossy)
source like DVD isn't the best to encode from.

Also, if you're re-encoding rather than from the original DVD Rip then
you'll have further losses.

Like I suggested before, play around with the settings, like Rate Factor
(rf/crf), to get different results. Remember, a lower number is a higher
quality (longer time to encode) and a larger number is a lower quality
(less time).
On Thu, Apr 6, 2017, 6:48 PM Alexisback <notifications@github.com> wrote:

I did a couple of tests with version 6
the result is good, however, the definition of the details and a bit blurry
how to adjust this?

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/Anime4000/IFME/issues/113#issuecomment-292084384>, or mute
the thread

**Comment by Alexisback** [comment]
I set these values in the "custom profile"
Preset= medium
Rate Control= single pass <--------it's right ???
Value= 20

which it is preferable for this?
preset = ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow,placebo

and this?
tune = psnr,ssim,grain,zerolatency,fastdecode

![picture](https://cloud.githubusercontent.com/assets/18039740/24748125/637b7194-1ac7-11e7-9f4c-c2e7d6faf115.png)

![video](https://cloud.githubusercontent.com/assets/18039740/24748132/695fcf92-1ac7-11e7-8c0f-0470e68bc41c.png)

**Comment by thefinaldegree** [comment]
Again, there's no 'right' or 'correct' setting. I would suggest reading
through the previously mentioned guide or lookup an encoding guide in your
language.

**Comment by Alexisback** [comment]
I will go to trial, until I'll find the right settings

in my language, there are very few guides,
do not explain the setting
The H265 codec is not widely used, such as h264

**Comment by thefinaldegree** [comment]
You can use guides for h.264 as it's not too far different

**Comment by Anime4000** [comment]
this thread so old, use 7.x definition file. JSON script should be easy to read and edit.
Reopen if you have any question 😄
