### ISSUE TITLE
With MKV output, is it possible to do Variable Frame rate ?

### ISSUE THREAD

**Issue by Ryoandr** [Anime4000/IFME#152]
I can't find a way to add `timecode.txt` file, is it supported ?

**Comment by Anime4000** [comment]
- I drop VFR support since version 7, due to complexity to make it sync, some device can't play VFR, also editing VFR video cause bug, in this case Adobe Premiere/After Effects.

- if Source is VFR, it will be converted to Constant FPS.

- VFR is good for space saving, but modern codec like H.264, H.265, VP9 smart enough to create null frame or reference frame.

So... You want to add custom `timecode.txt` right? I think I can add this option before I release 7.6

**Comment by Anime4000** [comment]
sorry, for this feature will be implement on version 7.7 for custom `timecode.txt` for selected video stream.
How ever, IFME never output VFR (for compatible support)
