### ISSUE TITLE
Video completes gets error and other files in queue stop

### ISSUE THREAD

**Issue by OneVoltTen** [Anime4000/IFME#19]
Start encoding file, gets to end (mux) finishes encode (working) then puts out error:
The cue entries (the index) are being written... Muxing took 1 second.
Encoding canceled! Nope!
Is there a way to ignore issue and continue encoding regardless because I can't batch encode as it is, keep having to tell it to start for each separate episode.
I tested on another pc with exact same settings, it didn't have error.

error log: http://pastebin.com/0UXADWms

**Comment by SailorOnDaTea** [comment]
Check this:
https://github.com/Anime4000/IFME/issues/17#issuecomment-84086715

If you think it is the same issue then try this quick patch:
https://cdn.fbsbx.com/hphotos-xpf1/v/t59.2708-21/11010202_398172423696620_335855296_n.7z/Debug.7z?oh=c3a5c537a9bde03131ddd1636c477c97&oe=551ABE11&dl=1

**Comment by Anime4000** [comment]
mkvtoolnix exit by returning error code (1), but IFME mark 1 as error but mkvtoolnix error code is 2, 1 mean warning

that temporary patch should works :smile:

**Comment by OneVoltTen** [comment]
Thanks for the fast reply, testing now with an encode.
Are planning to add avisynth filters? (vafe): http://i.imgur.com/LENqk5x.png
I would be happy to donate if you are planning to.
Audio playback issues with Ogg and Passthrough (audio out of sync) (flac/lossless have no issues)
Are there any ways to avoid bad audio encode?
(When audio encoded in another program and muxed in and there is no playback issue.)

**Comment by OneVoltTen** [comment]
I did a few tests for the best encoding preset:
https://docs.google.com/spreadsheets/d/1uAbUuLWsuBHBKZMOpkz-0uA7kdZAa4AREbMstaIBjAE/edit#gid=0
Slower preset seems have to be the ideal compression:fps at the moment. If possible could you recommend any command line settings that help compression.
-thanks

**Comment by Anime4000** [comment]
@OneVoltTen IFME mainly use of preset, preset is a collection of command-line, you can refer here: http://x265.readthedocs.org/en/latest/presets.html

IFME also mainly use executable instead of API/Wrapping, this give low CPU overhead and work encoder faster,

I try to study AVISYNTH or any filter that I can add-on into, but this probably future version of IFME, (IFME Go, Go／五 mean 5 in Japanese, -> version 5)

Future version will be advanced, since I starting to write from scratch and redefined Interface (with fall-back classic IFME style (all video share same settings, Many to 1 method)

Development wise, I just started developing it, not sure when I can complete, but I will do in parallel, mean I develop both version.

By mean `probably`, I can't guarantee if I can implement, since I use FFmpeg to read input and decode, IF... AVISYNTH can read universally of video codec into RAW format via PIPE, 100% I can implement :smile: just matter of time to study and understanding :) these stuff

**Comment by SailorOnDaTea** [comment]
have you checked mencoder stuff? I think it supports pipelining. mostly for legacy format support like real media and as an alternative decoder.

Avisync sounds good as well!

btw i found out that we cant add multiple subtitle for one video. for example: eng fra ger jpn, and think about tv series, many files.. but i guess you will take care of it in 五。 you said it would support individual settings.
Later I batch muxed my subs with ffmpeg but then I couldnt set their language tags XD dont forget about this in new version, subtitle language tag.

--- Original Message ---

**Comment by Anime4000** [comment]
Next version, IFME (4.9.5) will support AviSynth script :+1:
Take a look: [Facebook Page](https://www.facebook.com/internetfriendlymediaencoder/photos/a.290051507842046.1073741828.290041474509716/405296039650925/)

Sample that I made using 60fps script [Video Sample](https://drive.google.com/uc?export=download&id=0B_nmcRzQ-bL9ZWxjZmt1M2ZONVk) & [Logs](https://drive.google.com/uc?export=download&id=0B_nmcRzQ-bL9eExJY2hibGNuVGM)

**Comment by OneVoltTen** [comment]
@Anime4000 Thanks for the update, looks awesome. Will try it now :)
Though 5h 41m encode :3
