### ISSUE TITLE
Some Major and Minor questions?

### ISSUE THREAD

**Issue by TwistedFaith84** [Anime4000/IFME#195]
Hey I just downloaded your ~updated~ version and was wondering
1) what happened to all the other encoders?
2) what happened to the general info page?
3) does/will IFME support GPU acceleration (such as if you have NVIDIA, AMD, INTEL, or Other GPU)?
4) does/will it support CPU acceleration (I know the new Ryzen CPU's can out perform anything for encoding/decoding) (for proof https://youtu.be/JwETLRMandY)? 
5) is this going to be an installable program (like it used to be)? or are you going portable with it?

**Comment by Anime4000** [comment]
Answer to your question

1. If you mean encoder codec, this soon will be added, reduce bug when I working on, for now I using modern encoder like `x264`, `x265`, `AV1`

2. General info aka Media Info also not available at this time, I thinking using `Right-Click > Properties` approach, reduce memory footprint instead put everything on RAM. like previous version, one video take ~900KiB for Media Info, Encoding Settings, During encoding, and more... when do batch encoding, IFME can use so much memory.

3. My original plan, not to include GPU Accelerated encoding, main goal is to make file size small as possible with highest quality, also IFME relaying heavily on `FFmpeg`. I believe `FFmpeg` has GPU accelerated encoding, this will be integrated at stable release, I need GPGPU detection engine, so IFME can decide which one to use (AMD/NVidia), also add more loading time since to detect host hardware, also I do AMD first since I using AMD GPU.

4. Yes! Because someone donate new AMD Ryzen 3950X, Asus Motherboard and RAM, so IFME build on top Ryzen system, also... `x265` is compiled toward AMD Zen 2 Architecture. `x265` encoding are much faster at right settings.
```
Compiler: GCC 9.3.0 + znver2
Build: x265 3.2 stable
Resolution: 4K @ 10-bit
Options: medium preset, psnr
```
![3501467477-Internet Friendly Media Encoder 20 02](https://user-images.githubusercontent.com/1908715/80365636-83844600-88ba-11ea-926f-c2b9d6bed728.png)
![4033918161-Task Manager](https://user-images.githubusercontent.com/1908715/80365650-867f3680-88ba-11ea-9df4-f5e2bba030bc.png)


5. Installer will included when stable release, for alpha/beta only available on `zip` package, so you can delete old, keep old or replace existing

bit by bit, IFME will complete.

**Comment by TwistedFaith84** [comment]
1) Yeah sorry I did mean encoder codecs. and ok that's understandable.

2) ok that sounds good as long as its something that can stay up (till you close it) that way you can view what the original properties of the file were in case you just wanted to have everything be the same except for maybe a different video bitdepth, audio channels or bitrate, or something like that

3) ok. yeah I don't really know anything about ffmpeg (or similar). I especially don't know any of the coding lingo (parameters) for advanced/expert setting and such.

4) Oh you Luckily BAS***D. LOL.

5) Ok that sound good. Now when you say replace existing do you mean like a copy and paste job or replace as in just use this instead? If's it a copy and paste job; what can/can't I copy/replace from either new 2 old or old 2 new (most likely new 2 old (copying new file/s and pasting in old directory) or would it be better the other way around)

**Comment by Anime4000** [comment]
>     5. Ok that sound good. Now when you say replace existing do you mean like a copy and paste job or replace as in just use this instead? If's it a copy and paste job; what can/can't I copy/replace from either new 2 old or old 2 new (most likely new 2 old (copying new file/s and pasting in old directory) or would it be better the other way around)

You may keep previous build if newer have bug, let say you keep software version like this:
```
ifme-7.7
ifme-20.04.1_debug
ifme-20.04.2_debug
...
ifme-20.x.x_release
```
Very useful for non-stable release, you can go back previous build without re-downloading.

The installer useful at stable build and always replace old version.

**Comment by TwistedFaith84** [comment]
I'm not that worried about re-downloading

**Comment by Anime4000** [comment]
i see, for now I release in `zip` package. stable will have both `installer` and `zip`

**Comment by Anime4000** [comment]
alright, this fixed version I made, hope it helps
https://github.com/Anime4000/IFME/releases/tag/20.05.2-alpha
