### ISSUE TITLE
New version (IFME-21.05.25_Debug) takes incredibly long time to load

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#216]
Thank you for the new version.

Just tried IFME-21.05.25_Debug on two different computers. 

Here are some issues:
1) It takes incredibly long time to load. Times out on many things. Can those be removed? 
2) I know its still debug release but can you allow settings? That way a few options can be reduced.
3) It works on one computer but does not work another computer. Not sure what the issue is. No matter what source video I take, it gives following error:
===========================================================
Internet Friendly Media Encoder 21.05.25 ( 'One More Time' )
Build: IFME v21.05.25 windows amd64 znver2 (Zen 2 architecture)

(c) 2021 Anime4000, MulticoreWare, VideoLAN, FFmpeg, Xiph.Org Foundation, Google Inc., Nero AG, GPAC, AMD, Intel, Nvidia et al.

Warning, DO NOT close this Terminal/Console, all useful info will be shown here.

[INFO] Selected format (container) doesn't support video: Object reference not set to an instance of an object.
[INFO] Selected format (container) doesn't support video: Object reference not set to an instance of an object.
[INFO] Extracting subtitle file...
[INFO] Extracting embeded attachment...
size=       0kB time=-577014:32:22.77 bitrate=N/A speed=N/A    
[INFO] Extract audio file...
[INFO] Encoding audio file...
===========================================================

Not sure what it means by Selected format (container) doesn't support video. Because on the other computer it works just fine for the same source video. Clearly, this is my other computer issue but both are Windows 10 (latest patch). The older version of IFME works fine on both computers. So let me know if there are any settings I need to tweak.

4) More information on the 2nd computer. When I start IFME, it is not able to load all the encoders. It only loads AV1, copy and x264. Maybe that is causing the issue. Not sure why it is not able to load any x265 (including Multicore) encoders. It loads them fine on the other machine where I can see all 4 of them. Any thoughts? Maybe the PC does not support multicore?

**Comment by Anime4000** [comment]
May I know what processor (specification) are you try on?

I sorry to rush thing, MulticoreWare devs have change a lot and I just noticed it didn't work on Intel i7 3770K

Works on my AMD Ryzen 9 3950X but not work on my Intel i7 3770K.
Since I compile on my AMD system, it looks AVX256, i7 3770K lacks of AVX256, so, x265 failed.

Currently I working on µArch to detect host system which feature, either SSE3S, SSE4.1, AVX128 or AVX256
this ensure maximum efficiency and encoding speed.

The loading screen had to test encoders via samples file before it fail on big video's, it may load faster on mid-rage system.
In next update, I put small sample file.

**Comment by Anime4000** [comment]
using small sample file for now
