### ISSUE TITLE
Issues with latest version

### ISSUE THREAD

**Issue by canbonbon** [Anime4000/IFME#218]
Hello Anime4000
I am now using the new version IFME-21.06.14_Debug.7z. It has fixed the issue of not being able to run on the older computer. So thank you for that. However, some other issues have come up:
1) The rate factor is now fixed at 28. No matter what value I give for the rate factor, its ignoring the value from the UI and defaulting to 28.
2) It also loads faster maybe because the sample file is small. But my question is do you really need to do that? Why not let people configure the HEVC encoder they want in settings. That way, this unnecessary check can be avoided. You are spending time checking all kinds of encoders but I only use one "x265 Mulitcoreware". So I don't really need the others. If I could change that in the settings then the long checks for those can be avoided
3) Can you please open the settings?
4) I have modified your default JSONs to tweak some parameters for me because I use those almost all the time. But I am not able to figure out how to default "COPY Audio" checkbox. I never transcode the audio, is there a JSON that I can modify so that I don't have to check that box every time? That would be very helpful.
5) I see that you have now changed the default "Tune" to "psnr". In the previous versions it used to be "ssim". Any reason to do that? Ever since Dr Wang got the Emmy award for SSIM algorithm, I have been using that. Did your results show psnr being better than ssim?
6) Finally, can you please remove the "_encoded" from the end of the file? Its one more thing I do before I move the video to my library. Once again unnecessary step that can be avoided or changed in the settings.

Other than that it seems to be working great for now. I will give more feedback as I use it more. Thanks again for all your effort.

**Comment by Anime4000** [comment]
Hi @canbonbon 

Here some answer:

1. I just notice I been using `ValueChanged` event which is trigger when using scroll bar, up, down key. I just check when typing the value and event not fired. This will get fixed by merging events `ValueChanged` and `Leave`.
2. For now, IFME had to check encoder on host computer to avoid "broken" or "error" while encoding in the future, for now IFME need check all encoder, in beta release you can disable encoders in Settings Window
3. Settings window is Work In Progress, in past experience some user have lost his files when set wrong `temp` folder, I need to finish fool proof first.
4. Next version, Audio Copy checkbox is gone, replace with **Copy Stream** like in Video Tab, and Audio copy will be default selection.
5. I see, next version for x264 and x265 will be default SSIM. I choose PSNR because give a bit smaller file size...
6. Prefix/Postfix file name will available in beta as Settings window exist.

all critical bug will fix immediately

**Comment by Anime4000** [comment]
Like this? Disable unused encoders for faster startup
![Options 2](https://user-images.githubusercontent.com/1908715/122291714-b3abff80-cf27-11eb-85ca-ec38813e5366.png)

**Comment by Anime4000** [comment]
@canbonbon Try this,
https://sourceforge.net/projects/ifme/files/encoder-gui/21.x/IFME-21.06.17_Debug.7z/download

**Comment by canbonbon** [comment]
Wow, this is awesome. Thank you for resolving two main pain points for me. I was able choose just HEVC in the settings and now it loads crazy fast. Copy audio is the default option so I don't have to go and check it all the time. I will test it with multiple tracks and see if copies all of them or not. Rate factor setting now works as well and I normally set to 23. And finally, SSIM is now the default. So all great fixes and once again thank you for that. It seems you have fixed pretty much all of the issues I have reported above. I will now start doing 2160p HDR conversions and give you some feedback on those as well.
