### ISSUE TITLE
Where is NeroAAC?

### ISSUE THREAD

**Issue by devlin85** [Anime4000/IFME#31]
It is listed on the website and release history from 7 months ago but is not anywhere to be found. And literally nowhere else on the internet that I can find.

"Another AAC encoder alternative to FFmpeg and FAAC, thanks to SailorOnDaTea providing this.
Download: From SourceForge (http://sourceforge.net/projects/ifme/files/addons/windows/neroaac.ifz/download)"

**Comment by Anime4000** [comment]
Nero [Licensing and Agreement](http://www.nero.com/eng/company/about-nero/nero-aac-codec.php)
> This License does not provide any rights to reproduce and/or distribute this software package in whole or in any part.

Mean I can't distribute Nero within IFME.
I can provide definition file, and you need download it manually
https://github.com/Anime4000/IFME/releases/tag/v5.0-beta.9a

**Comment by SailorOnDaTea** [comment]
http://www.nero.com/eng/company/about-nero/nero-aac-codec.php

 you should download binary(exe) from nero's site(above link)

agree, enter email, download zip.

if you dont want to give your email, you can use sth like

temp-mail.org

you only need neroaacenc.exe  in win32 folder from that zip file.

and this 5.x won't work with ifme 4.x versions. 

just copy that exe inside neroaac folder.

**Comment by SailorOnDaTea** [comment]
btw, that ifz was for ifme v4. Back then we needed to make seperate folder for each mode (cbr,vbr,abr etc...) They shared single exe inside "neroaac" folder but one addon needed a number of folders.

Right now (with ifme go) you can use 1 folder for each addon, all INI files and EXE for that addon are inside single folder.

**Comment by Drive251** [comment]
sorry, i know this closed but can we replace it with qaac 
https://sites.google.com/site/qaacpage/
https://github.com/nu774/qaac

**Comment by Anime4000** [comment]
ok... in the future, IFME 5.2 will have qaac included... hope no redistribute restriction...

**Comment by SailorOnDaTea** [comment]
qaac needs some Apple software installed. it won't do anything on its own.

**Comment by Anime4000** [comment]
yea... I tried that, can't ship qaac :(

**Comment by SailorOnDaTea** [comment]
Actually Nero is easier and lightweight(only one exe, simple parameters) but I also made a few files to use qaac with ifme. For basics, these should work. This is my skydrive/onedrive. These are ini files fixed to include "arch ="

https://onedrive.live.com/redir?resid=6C7F09DE3FC7148C!13315&authkey=!ABMLkSIsPYRyEfY&ithint=folder%2c

qaac files are available here:
https://sites.google.com/site/qaacpage/

you can check for latest version there or use as is, but normally you should get exe and ddl from source.
I tried to explain on FB page how it works but I don't have a blogging or similar habit so just use if my files suit your needs.

We can make a list of plugins and link them. so users can download whatever they want from wherever available. many audio encoders have license restrictions and there are several types of each fitting different tastes. instead of picking one for all, developer can let everybody use what they want. FAAC is already included as basic and others may or may not want to install extra stuff.

**Comment by Drive251** [comment]
SailorOnDaTea and Anime4000, thank you for the reply

**Comment by kuh3h3** [comment]
i  tried qaac 2.58 plugin in recent ifme 6 x64 experimental.
changed version number to 2.58.
but ifme can`t find qaac plugin. need any guid setting?
qaac  itself works well.

Microsoft Windows [Version 10.0.10586]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Administrator>cd C:\Program Files\Internet Friendly Media Encoder\plugins\qaac64

C:\Program Files\Internet Friendly Media Encoder\plugins\qaac64>qaac64 --check
qaac 2.58, CoreAudioToolbox 7.10.5.0
libsoxconvolver 0.1.0
libsoxr-0.1.1
libsndfile-1.0.26
libFLAC 1.3.1
wavpackdll 4.80.0

C:\Program Files\Internet Friendly Media Encoder\plugins\qaac64>
