### ISSUE TITLE
2 portable installation on the same computer can't encode at the same time.

### ISSUE THREAD

**Issue by WillGunn** [Anime4000/IFME#61]
If you install ifme twice in portable mode to different locations, they are unable to encode at the same time (I need 3 iterations running to max out my cpu).

**Comment by Anime4000** [comment]
installing 2 different location cause sharing same configuration: `%APPDATA%\..\Local\Hitoha_Project`. I notice this issue when CPU didn't max 100% either MSCV/Intel C Compiler, in GNU just work fine.

Try modify CPU Affinity on Task Manager:
1. find x265
2. Right click → Set Affinity
3. Uncheck all, leaving CPU0 checked.
4. Click OK
5. Right click x265 again → Set Affinity
6. Check all
7. Click OK.

**Comment by SailorOnDaTea** [comment]
okay, to put it simply, there are two problems:

1- second instance of ifme wont encode. gui works fine but gives error on CLI.
2-speed won't rise even when CPU load is still half,HDD is IDLE, RAM is idle. All cores work, but total load will only saturate 4 cores. it doesnt matter which core, which chip or which socket. speed is limited for some unknown reason. I get around 18 fps while expecting over 30... If I didn't have this issue, I wouldn't worry about the first one.

**Comment by Anime4000** [comment]
on my 6 core AMD, it will all cores when encoder 4K, (GCC)
intel and microsoft do the same, I fix this if not sure, try see 5.1.4 pre-release

on Linux just work flawlessly

**Comment by SailorOnDaTea** [comment]
After I encountered same bug on my core2duo(which was working fine before), I decided to check if it is related to .NET updates on windows. Before trying patch, I will try to pinpoint the main reason. If it is about .NET versions, then I want to know which version causes it. I will report you on FB.

**Comment by Anime4000** [comment]
way it works, in Linux, x265 spawn many child process, I not sure how Windows works

**Comment by SailorOnDaTea** [comment]
long time passed since we talked about this but i concluded that h265encoder itself, by its nature, unable to max out all cores with lower resolution videos. this might be due to pipelined workflow, wait chain, rather than parallelization issues or hardware infrastructure bottlenecks. 

as a workaround, running as different user under windows can overcome this issue. When you right click on ifme while holding shift key it lets you choose running under different user account(like back in xp days) this way it won't overlap with current running program. both can work at the same time.
