### ISSUE TITLE
Folder or filename with a quote

### ISSUE THREAD

**Issue by skrew** [Anime4000/IFME#81]
Hi,

On Linux, adding a folder or a filename with a quote cause a crash.

EG: L'univers

**Comment by Anime4000** [comment]
have you try `\"` ?

**Comment by skrew** [comment]
I can't, i use it with the GUI application.

**Comment by Anime4000** [comment]
this seem `mono runtime` limitation, wait... I trying on my VM

**Comment by Anime4000** [comment]
If you using 6.0 error was:
https://github.com/Anime4000/FFmpegDotNet/blob/master/FFmpegDotNet/Run.cs#L28

If you using 5.x issue was:
https://github.com/Anime4000/IFME/blob/master/ifme/TaskManager.cs#L44

common problem: `sh -c 'command here'`

in windows, char `"` illegal, linux not, meanwhile `'` both OS accept as file name... so...

**Comment by skrew** [comment]
Just to be clear, the crash come with a single quote: `'` not double quote: `"`

**Comment by Anime4000** [comment]
Yes, it crash because I instruct IFME to execute `bash -c 'command'` when file name has `'` char, `bash` stop read at last `'` char, rest of it consider other arguments, for example:

```
bash -c `echo "foobar"`
```
result: `foobar`

```
bash -c `echo "foo'bar"`
```
result: `> ` waiting input, error

fix is:
```
bash -c "echo \"foo'bar\""
```
result: `foo'bar`

Linux very sensitive :cry: unlike Windows...

![virtualbox_ubuntu 14 04 3 64-bit _28_01_2016_07_10_54](https://cloud.githubusercontent.com/assets/1908715/12631777/4c8b5c72-c58e-11e5-9bcd-43e599e61fbf.png)

**Comment by skrew** [comment]
Hehe yep, but it's a bug resolved fast ! ;)

**Comment by Anime4000** [comment]
and then... another better [solution](http://unix.stackexchange.com/a/124593), using `eval` instead of `bash -c` or `sh -c`

hold on :smile:

**Comment by Anime4000** [comment]
commit done! try recompile :smile:
